### ISSUE TITLE
Having a loading indicator would be great!

### ISSUE THREAD

**Issue by kavinda1995** [i18next/i18next-resource-translator#1]
## 🚀 Feature Proposal

Right now, whenever the user has given a big json file to translate - it takes at least few seconds to load the data and show it in the translated view. This is expected, since the translation takes some time - but it's not a good UX to the user. For example, when I first tried the app - I actually closed the app thinking this don't work as I don't have any indication that's something running or not. So it's better to have a loading indicator to denote that things are in work in background.

I would like to send a PR with this improvement if agreed upon the requirement

**Comment by adrai** [comment]
This is just the dist repo... the sources are not there... so you can't create a PR for that... but we'll check if we can create a loading indicator asap

**Comment by adrai** [comment]
just done so...
<img width="1499" alt="image" src="https://github.com/i18next/i18next-resource-translator/assets/1086194/cb1ac716-8047-4f8c-ae3a-d850953c2168">

btW: If you often use translate.i18next.com please consider to use locize... this will directly support the future of i18next...

**Comment by kavinda1995** [comment]
Great! Thank you very much for the prompt fix :). We already do, just tried this for a partial translation
