### ISSUE TITLE
Truncated translations and google api URL pollution

### ISSUE THREAD

**Issue by Miltant** [i18next/i18next-resource-translator#2]
## 🐛 Bug Report

The source values are not properly url encoded before being submitted to the google translate API, sometimes resulting in truncated results and/or url params pollution.

## Example 1: Truncated result
Translate the following, from `en` to `en`:
```json
{
  "key": "value1 & value2"
}
```

It outputs:
```json
{
  "key": "value1"
}
```

## Example 2: URL param pollution
```json
{
  "key": "value&dj=1"
}
```

`dj` changes the formatting of the google translate response in a way that the i18next translator client cannot parse, outputting an empty value:
```json
{
  "key": ""
}
```

## Expected behaviour

The string should be url encoded in order to be processed fully.

**Comment by adrai** [comment]
should be addressed now
