### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by samturrell** [i18next/i18next-resource-translator#3]
Hi there!

Super useful tool, and i make use of it fairly extensively, there are just a few things that would make it easier to use.

## 🚀 Feature Proposal

1. "Copy" button next to "Download".

2. Validate the JSON before translating.

3. Store the selected language in a cookie, or localStorage.

## Motivation

1. Often i have my IDE up, and i'm copying an english translations file into the tool, and then pasting directly into the other language files. Currently it's a bit awkard to copy, especially with large translation files, you often aren't focussed on the correct element and end up highlighting the entire page.

2. Currently if you paste invalid JSON, with as little as a trailing comma, the tool throws an unreocerable error, and you have to refresh.

3. I come back to the tool fairly often, and have to set the language again, even thought it's always the same when i use it.

## Example

N/A - self explainatory

**Comment by adrai** [comment]
@samturrell just adapted for this enhancements... but honestly, if you come back to the tool fairly often, you may think of using our translation management system ([locize](https://locize.com)) and support us, instead of only using this "limited" showcase...

https://youtu.be/TFV_vhJs5DY
